# syntax = docker/dockerfile:1.0-experimental
FROM base_dev_image:latest as base_dev_qt5_image
FROM base_dev_qt5_image:latest as rpi_dev_qt5_image

#USER root


# crossbuild-essential-armhf

RUN apt-get update &&  \
    apt-get install -y \
    crossbuild-essential-arm64
